# Nordic palette for Kitty
foreground            #C0C8D8
background            #242933
selection_foreground  #C0C8D8
selection_background  #2E3440
cursor                #C0C8D8
cursor_text_color     #242933
url_color             #88C0D0
active_border_color   #2E3440
inactive_border_color #2E3440
bell_border_color     #BF616A
inactive_text_alpha   1.0
draw_minimal_borders  yes

tab_bar_edge            top
tab_bar_background      #242933
active_tab_foreground   #C0C8D8
active_tab_background   #242933
inactive_tab_foreground #4C566A
inactive_tab_background #242933

color0  #191D24
color8  #3B4252
color1  #BF616A
color9  #C5727A
color2  #A3BE8C
color10 #B1C89D
color3  #EBCB8B
color11 #EFD49F
color4  #5E81AC
color12 #88C0D0
color5  #B48EAD
color13 #BE9DB8
color6  #8FBCBB
color14 #9FC6C5
color7  #C0C8D8
color15 #D8DEE9
